### ISSUE TITLE
Согласование ШИМов разных плат

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#102]
Почему-то ШИМ который генер т плата сас крашит все ШИМ сигналы

**Comment by PugachA** [comment]
Предлагаю попробовать:

- [ ] Запитать сервы отдельно от двигателя
- [ ] Сделать идентичные настройки ШИМ на двух платах. Поднять частоту.
- [ ] Добавить логгирование передаваемого ШИМ на двигатель

@NoMonsters  Что еще можно?

**Comment by NoMonsters** [comment]
Мб:

- [ ] Тебе использовать RcChannel, а не PWMCapture
- [ ] Использовать Servo с микросекундами а не градусы

**Comment by PugachA** [comment]
Отловили ошибка, когда полностью умирает плата САС. Это происходит при большой нагрузке на сеть питания 3.3В, напряжение проседает и плате не хватает питания. Поднята напряжение на стабилизаторе и ошибка устранена

**Comment by PugachA** [comment]
Нужно отловить кейс, когда появляются задержки на всех сервах
