### ISSUE TITLE
Оценить частоты работы систем

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#11]
Оценить какова частота опроса сенсоров, каналов управления, управления сервоприводами двигателем. Оценить быстрдействие контроллера для этих целей и возможности ОС. Исходя из этих данных выбирать и подход использования ОС

**Comment by NoMonsters** [comment]
@Li2s  Есть какие-то идеи, кроме тех что мы обсуждали? Не спрашивал у коллег на работе?

**Comment by Li2s** [comment]
> @Li2s Есть какие-то идеи, кроме тех что мы обсуждали? Не спрашивал у коллег на работе?

Возможно получится узнать на след неделе

**Comment by NoMonsters** [comment]
Задача не туманная
Никто не сделал и делать не будет.
Очень неконкретная
впизду её
