### ISSUE TITLE
Задержка всех сервоприводов

### ISSUE THREAD

**Issue by PugachA** [PugachA/UnmannedAerialVehicle#111]
Возникает ситуация, когда все сервы воспроизводят сигнал с задержкой. В домашних условиях это отловить не удалось.

**Comment by NoMonsters** [comment]
Не воспроизводится. Скорее всего проблемы была в нехватке питания, т.к. от этого же регуля питается и основной контроллер и логгер. После установки нужного напряжения проблема не воспроизводится.
Считаю что проблема решена. @PugachA @Li2s ?

**Comment by Li2s** [comment]
Предлагаю закрыть после успешного полёта.

**Comment by NoMonsters** [comment]
В полете не воспроизвели, закрываю баг
