### ISSUE TITLE
Добавить TrimReset на одну из кнопок пульта

### ISSUE THREAD

**Issue by Li2s** [PugachA/UnmannedAerialVehicle#119]
Избавляемся от следующего кейса:
1) Летим вручную, оттримировали все каналы, средние значения уехали с 1500 мес
2) Включаем стабилизацию, маппинг мкс ШИМ->заданная угловая скорость сделан из расчета, что 1500 мкс-> 0 гр/с. При нулевом положении ручке заданная угловая скорость не ноль.

**Comment by NoMonsters** [comment]
Решили, что вся логика будет на пульте, посмотреть что в OpenTx можно по этому поводу. Желательно, чтобы при возврате в ручной режим триммеры вернулись в установленные ранее пилотом значения.
Во всех режимах кроме ручного тримы в 0

**Comment by NoMonsters** [comment]
Добавил обнуление тримеров в пульте используя flight mode. При положении тумблера соответствующего стабилизации триммеры обнуляются и недоступны, при других положениях стиков они возвращаются в старые значения
