### ISSUE TITLE
Проверить напряжение после реле

### ISSUE THREAD

**Issue by PugachA** [PugachA/UnmannedAerialVehicle#12]
Необходимо проверить не просидает ли напряжение после реле.

**Comment by NoMonsters** [comment]
Это ещё актуально? Будешь это делать? Давай тогда же когда будем собирать самолет у меня проверим.

**Comment by PugachA** [comment]
Да, актуально, сделаем

**Comment by NoMonsters** [comment]
Неактуально. Реле слишком слабое для наших целей. Нужно найти подходящее на 16 В, 30-50 А.
