### ISSUE TITLE
Сделать новые шасси

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#133]
Текущие шасси слишком хлипкие для этого самолета. Колеса норм, сами опоры слабые. Носовая вечно гнется. Продумать замену. Но это супер сложно мб, т.к. всё очень вклеено и закрыто

**Comment by NoMonsters** [comment]
@Li2s поищи чего есть по шасси и отпиши сюда плз

**Comment by PugachA** [comment]
@Li2s Нашел что-то?

**Comment by NoMonsters** [comment]
Rejected
