### ISSUE TITLE
Подобрать кэфы для фильтра H и апериодических звеньев для дифф-ра

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#144]

**Comment by NoMonsters** [comment]
Замерить период вызова, чтоб посчитать в модели эти кэфы

**Comment by Li2s** [comment]
[diff_filter.zip](https://github.com/PugachA/UnmannedAerialVehicle/files/5856925/diff_filter.zip)
Тут модель в дискретном времени с шагом 0.01 с. Интеграторы считают трапециями, думаю это не критично. То, что мы видели на железке, совсем с этим не сходится, думаю бага в коде, однако я тестил этот же самый код, отдельно работал.

**Comment by NoMonsters** [comment]
ну вроде чета подобрали
