### ISSUE TITLE
Сделать питание от отдельного акка для ERS

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#154]
Т.к. при питании телемы от стаба серв (от него же питается радио приемник управления) ловим помехи, режимы скачут произвольно и вообще пиздец

**Comment by PugachA** [comment]
@NoMonsters  Я бы назвал это отдельное питание для платы ERS

**Comment by NoMonsters** [comment]
Развел питание схема следующая:
![изображение](https://user-images.githubusercontent.com/33801216/111194806-9be17a00-85cc-11eb-8bef-73ed472e68c0.png)
