### ISSUE TITLE
Сделать стаб Vy черех ОмегаZ стаб

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#155]

**Comment by Li2s** [comment]
Сделал следующим образом: заданная вертикальная скорость формируется от ручки. Заданная угловая скорость тангажа формируется как выход пропорционального регулятора по ошибке вертикальной скорости. Заданные угловые скорости крена и рыскания формируются просто от ручки. Далее в каждом канале работает ПИ-регулятор по угловой скорости, как была стаба до этого.

**Comment by Li2s** [comment]
@NoMonsters надо тестить соответствующую ветку

**Comment by Li2s** [comment]
done
