### ISSUE TITLE
Сделать рилтайм рисовалку логов

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#156]
Надо ещё как-то обозвать её поумному чтоб нам было понятно о чем речь

**Comment by PugachA** [comment]
Наземная станция
Визуализация логов
PFD

**Comment by NoMonsters** [comment]
@PugachA 
К Сб/Вс нужно:
Сформируем мб пока строку специально для настройки кефов:
например: "омега_зад, омега_тек, Vy_zad, Vy_тек, k_омега, I_омега, k_vy"
Нужно, чтобы совместно на графике отображались омеги или вертикальные скорости и где-то ещё числовые значения кэфов, которые мы подбираем, не графиком.

**Comment by NoMonsters** [comment]
Ещё было бы прикольно передавать сигнал с канала режимов и согласно #157 отображать в каком режиме мы находимся, чтобы не путаться

**Comment by NoMonsters** [comment]
Формат:
`current_time;
10*omega_x_zad;
10*omega_x_tek;
10*omega_y_zad;
10*omega_y_tek;
10*omega_z_zad;
10*omega_z_tek;
100*baro_h_tek;
100*vy_zad;
100*vy_tek;
beta;
10*k_p_omega_x;
100*k_i_omega_x;
10*k_p_omega_y;
100*k_i_omega_y;
10*k_p_omega_z;
100*k_i_omega_z;
10*k_p_vy;
mode_switch_pwm`

Множитель перед параметрами - на что они домножаются чтобы в строке были инты при передаче, т.е. при отображении параметр надо разделить на соответствующий множитель

Отображение:
экран1: 

1. График текущей и заданной омеги на одном плоттере
2. Где-то рядом числовые значения кэфов k_p_omega и k_i_omega
3. Где-то ещё рядом поле с названием режима полета #157 описаны диапазоны. Дополню табличку названиями режимов сегодня поздно. Определяется параметром `mode_switch_pwm`

экран2:
1. График текущей и заданной вертикальной скорости на одном плоттере
2. Где-то рядом числовые значения кэфа k_p_vy
3. аналогично экарн1

**Comment by PugachA** [comment]
Сделано
