### ISSUE TITLE
Реализовать СИ ВСП

### ISSUE THREAD

**Issue by Li2s** [PugachA/UnmannedAerialVehicle#16]
- [x] Считать данные с MS5611
- [x] Реализовать фильтр для получения вертикальной скорости

**Comment by Li2s** [comment]
@NoMonsters @PugachA прошу вас оценить реализацию опроса MS5611 в классе, представленную в ветке feature/add-MS5611-lib

**Comment by PugachA** [comment]
Никит, так не делается. Нужно создать PR, чтобы нам было удобно проверять изменения. Был удобный инструмент сравнения. И в PR можно ставить Апрув или реджект

**Comment by Li2s** [comment]
@PugachA это не пойдет даже в девелоп, поскольку плата поменяется, только поэтому не стал создавать PR

**Comment by NoMonsters** [comment]
Фильтры реализовывать по #21

**Comment by NoMonsters** [comment]
@Li2s  Тут открыть отдельно issue на флюгарку и на ПВД для скоростного напора эту issue закрыть.
