### ISSUE TITLE
ERS радиоуправление

### ISSUE THREAD

**Issue by PugachA** [PugachA/UnmannedAerialVehicle#2]
**Краткое описание:** Пилот отправляет с пульта ДУ сигнал на использование САС, система выпускает парашют

**Предусловия**: пилот отправил сигнал САС

**Основной поток:**
1. Радиоприемник получает от пульта ДУ сигнал САС
2. Приемник передает сигнал САС на резервную плату
3. Резервная плата переключает ШИМ от основного контроллера, на свой ШИМ, который соответствует 0 оборотов двигателя
4. Двигатель останавливается
5. Резервная плата отправляет на сервопривод сигнал на открытие люка
6. Сервопривод открывает люк

**Постусловия:**
Парашют выпущен

**Технические детали:**
 - Используем дополнительный ШИМ резервного контроллера, скважность которого соответствует 0 об/мин (935 мкС) скорости вращения двигателя
 - Для переключения сигнала с ШИМ основного контроллера на ШИМ резервного контроллера используем мультиплексор
 - Используем доп. ШИМ, т.к. если просто положить сигнальный провод на 0, двигатель останавливается слишком долго - 5 секунд

**Служат выполнению требования:**
#30 - про обработку сигнала с пульта ДУ

**Comment by NoMonsters** [comment]
Тут ты хочешь требования или что это?

**Comment by PugachA** [comment]
Да требования
