### ISSUE TITLE
Сборка в Keil

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#23]
Можно ли в Keil отделать папку со всем этим барахлом от папки с исходниками? Наверняка можно. Выши пулл реквесты невозможно ревьюить. Я буду их заворачивать пока тут не будет ответа, возможно или нет.

**Comment by Li2s** [comment]
Я не понял, что конкретно ты хочешь

**Comment by NoMonsters** [comment]
Я хочу, чтобы была папка в которой меняются только исходники проекта. И не было тыщу файлов .hueprjft .nikitalitus и прочих. Даже когда Саня сделал PR уже с добавленым барахлом, всё равно при просмотре разницы есть ещё 13 системных файлов. Это супер неудобно. И таким образом я хочу, чтобы если вы сделали изменение только в main.c в PR я видел только main.c

**Comment by Li2s** [comment]
В таком случае нужно отцеплять проект в Keil от контроля версий, как это было с машиной

**Comment by NoMonsters** [comment]
Т.е. там нет никаких средств, которые позволяют как-то отделить исходники?

**Comment by Li2s** [comment]
Кстати, если в pr выбирать только интересующий тебя коммит (как правило последний), то он не будет отображать все файлы, только измененные и соответствующие им бинарники (которые и не отображаются)

**Comment by PugachA** [comment]
Если посмотреть мои последние коммиты, там меняется только `.с` или `.срр` файл, ну и файл проекта `.foton`. В принципе достаточно читаемо. Я пытался засунуть его в ингор, но какого хрена он все равно отображается

**Comment by NoMonsters** [comment]
Понятно, смотрим диф по коммитам
