### ISSUE TITLE
Задержка выпуска парашюта

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#26]
#7 
Предлагаю отказаться от задержки в прерывании. В нем поднимать флаг, а все остальное в основном цикле.

**Comment by PugachA** [comment]
https://github.com/PugachA/UnmannedAerialVehicle/blob/86239bf573281aa815a9172e620d958962e7b110/ESS/Src/main.c#L269-L273

**Comment by NoMonsters** [comment]
Ну и че это же тоже сделали. Поч ничего не закрываем?

**Comment by NoMonsters** [comment]
Ну и че это же тоже сделали. Поч ничего не закрываем?
