### ISSUE TITLE
Начальная сборка БПЛА

### ISSUE THREAD

**Issue by PugachA** [PugachA/UnmannedAerialVehicle#27]
- [x] Собрать планер 
- [x] Закрепить сервоприводы
- [x] Установить двигатель
- [x] Установить основной вычислитель
- [x] Разместить САС с парашютом
- [x] Доработать хвост (сделать рули направлений)

**Comment by Li2s** [comment]
В субботу собираемся?

**Comment by NoMonsters** [comment]
Если хоть что-то придет
