### ISSUE TITLE
Аппаратная часть САС

### ISSUE THREAD

**Issue by PugachA** [PugachA/UnmannedAerialVehicle#3]
Прикинул примерную схему системы
![Untitled Diagram](https://user-images.githubusercontent.com/33941018/67607656-eff87e00-f78d-11e9-8009-31145e2e44a9.png)

**Comment by PugachA** [comment]
@NoMonsters  и @Li2s  призываю вас.

**Comment by NoMonsters** [comment]
Предлагаю в качестве сигнала HeartBeat переключать состояние какой-то ноги основной платы 1 раз в секунду и пока нет логера не использовать CAN. И ловить это как внешнее прерывание на плате САС по смене сигнала.

**Comment by Li2s** [comment]
Согласен с @NoMonsters

**Comment by PugachA** [comment]
Согласен

**Comment by NoMonsters** [comment]
В итоге всё равно должна иметь барометр, чтобы не открывать парашют при слишком малой высоте, иначе может быть ещё больше вреда
