### ISSUE TITLE
Про сигналы радиоприемника

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#30]
Обрабатывать сигнал с пульта. 
Вкл - длина импульса ШИМ больше 1800 мкС
Выкл - длина импульса ШИМ меньше 1000 мкС

**Comment by PugachA** [comment]
А что делать, когда сигнал в интервале (1000, 1800)?

**Comment by NoMonsters** [comment]
Ничего. У этого канала только 2 состояния.

**Comment by PugachA** [comment]
Так ничего и «Выкл» это одно и тоже?

**Comment by NoMonsters** [comment]
Я пологаю да, можно по вкл просто прекращать heartbeat, чтобы не плодить разные обработчики. Хотя не уверен корректно ли это.

**Comment by NoMonsters** [comment]
Так это реализовано, получается можно закрывать или как?
