### ISSUE TITLE
Измеритель углов атаки и скольжения

### ISSUE THREAD

**Issue by Li2s** [PugachA/UnmannedAerialVehicle#33]
Реализовать измеритель угла атаки / скольжения с помощью флюгарки.

**Comment by Li2s** [comment]
@PugachA обновил флюгарку, запускай в производство
[Флюгарка.zip](https://github.com/PugachA/UnmannedAerialVehicle/files/4241214/default.zip)

**Comment by PugachA** [comment]
Готово

**Comment by NoMonsters** [comment]
Выполнено, летали с ним в полет 2. Продолжаем в рамках #71
