### ISSUE TITLE
Корпус для STM32L4 Discovery

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#35]
Нарисовать и напечатать корпус на стойках, чтобы можно было провода снизу в пины заводить и при этом не терялась возможность использовать дисплей и джойстик.

**Comment by Li2s** [comment]
@NoMonsters можешь какую-нибудь примитивную схему набросать, как ты хочешь его расположить внутри самолета?

**Comment by Li2s** [comment]
@NoMonsters набросал такого рода корпус, посмотри
[l476box.zip](https://github.com/PugachA/UnmannedAerialVehicle/files/4232743/l476box.zip)

**Comment by PugachA** [comment]
Норм, можно печатать.

**Comment by PugachA** [comment]
Готово

**Comment by NoMonsters** [comment]
Ничего не готово, пока не проверили влезает ли туда плата вообще

**Comment by Li2s** [comment]
@NoMonsters этого ишака можно закрыть?

**Comment by NoMonsters** [comment]
Великолепная работа, я вами горжусь
