### ISSUE TITLE
Перегородки для ERS

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#36]
Нужно переделать перегородки для системы спасения, вырезать двери, навесить петли. 
Текущие перегородки не подходят.
Нужно добавить стойки, на которых будут держаться пружины в сжатом состоянии

**Comment by PugachA** [comment]
[Downloads.zip](https://github.com/PugachA/UnmannedAerialVehicle/files/4241874/Downloads.zip)

**Comment by PugachA** [comment]
Лови stl
[Vypuskatel_parashyuta.zip](https://github.com/PugachA/UnmannedAerialVehicle/files/4289397/Vypuskatel_parashyuta.zip)
