### ISSUE TITLE
Выбор ДУС и Акселерометров 

### ISSUE THREAD

**Issue by Li2s** [PugachA/UnmannedAerialVehicle#38]
Проанализировать рынок, подобрать современный аналог MPU6050. Если будет позволять стоимость, подобрать датчик, способный выдавать не только угловые скорости, но и угловое положение.

**Comment by Li2s** [comment]
В общем я за Bosch BNO055
https://pandao.ru/product/cde8bbb4-4d95-4efe-ab28-e739d324e8a7

**Comment by NoMonsters** [comment]
@Li2s закажи, закрой ишак, когда закажешь

**Comment by NoMonsters** [comment]
> В общем я за Bosch BNO055
> https://pandao.ru/product/cde8bbb4-4d95-4efe-ab28-e739d324e8a7

Выбрали этот. Никита заказал 24.03.2020
