### ISSUE TITLE
Система отключения двигателя

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#40]
Реализация на мультиплексоре:
![изображение](https://user-images.githubusercontent.com/33801216/77848319-911bb280-71cc-11ea-874f-17fce497ff3b.png)
![IMG_20200608_174212](https://user-images.githubusercontent.com/33801216/84044506-585c3e80-a9b0-11ea-81de-26fb8f8efc5f.jpg)

**Comment by NoMonsters** [comment]
Нет смысла коммутировать транзистором аккумулятор, т.к. у нас уже есть коммутатор такого тока- регуль двигателя. И чтобы отключить движок нужно просто сигнальный провод разомкнуть. А если сам регуль наебнется, то уж точно отрубится. Он прям 0.0000001% наебнется так, что выйдет просто на 100%

**Comment by NoMonsters** [comment]
У нашего регулятора задержка между отключением сигнального провода и отключением движка - 5 **секунд**

**Comment by NoMonsters** [comment]
[Первый вариант подхода]
[неактуально]

Начал изучать вопрос.
Используем полевой транзистор + драйвер. Драйвер нужен т.к. у транзистора управляющее напряжение выше логического на ногах MCU.
Примеры транзисторов: тут
Пример драйвера: тут и тут

Полезные ссылки:

    ссылка1 основные моменты подключения полевиков
    ссылка2 хороший пример с моделированием
    ссылка3 схема управления питанием с MCU

**Comment by NoMonsters** [comment]
@PugachA нах ты закрыл это же доки?! Это лишний раз доказывает, что хранит документацию в ишаках так себе идея

**Comment by Li2s** [comment]
Перенес на вики https://github.com/PugachA/UnmannedAerialVehicle/wiki/%5BERS%5D-Система-отключения-двигателя
