### ISSUE TITLE
Распределение интеграторов по таймерам

### ISSUE THREAD

**Issue by Li2s** [PugachA/UnmannedAerialVehicle#59]
Поскольку у нас будет несколько ПИ-регуляторов и несколько фильмов необходимо определиться с архитектурой - как распределить эти интеграторы по таймерам и какие частоты для них подобрать. 
Пока кроме подхода, который мы использовали в машине (if в суперцикле по условию определенного количества переполнений определенного таймера) ничего в голову не приходит.

**Comment by NoMonsters** [comment]
Если @PugachA  намутит нам фриртос, то будем делать с ней

**Comment by NoMonsters** [comment]
Неактуально
