### ISSUE TITLE
Первичная реализация системы стабилизации

### ISSUE THREAD

**Issue by NoMonsters** [PugachA/UnmannedAerialVehicle#8]
Необходимо написать алгоритм формирования управляющего воздействия на сервоприводы для стабилизации ЛА.

**Comment by Li2s** [comment]
Программный код или структурную схему?

**Comment by NoMonsters** [comment]
Для начала структурно, см. требования. Сделай в проекте колонку `helper` с лйблом `description`. Добавь туда описание системы которую хочешь создать через `issue`. См. проект САС как пример.

**Comment by Li2s** [comment]
@NoMonsters колонку helper типа как in progress / done?

**Comment by NoMonsters** [comment]
Нет, helper больше не будет. Это просто как трекер ваших активностей. Не забывайте актуализировать

**Comment by NoMonsters** [comment]
Тоже какая-то хуйня, никто не делает. Откроем чета потом по мере надобности
