### ISSUE TITLE
Аппаратные доработки платы с датчиками для ERS

### ISSUE THREAD

**Issue by PugachA** [PugachA/UnmannedAerialVehicle#90]
- [x] Сделать разводку сигнала канала(ERS, Arming) пульта на плату ERS.
- [x] Подготовить место для модуля телеметрии 5V, RX, TX, GND.
- [x] Проверить корретность работы зеленного светодиода. По-моему последний раз он замыкание давал

![photo_2020-10-17_23-51-49](https://user-images.githubusercontent.com/33941018/96353355-cab5fb80-10d3-11eb-9dd9-43be21e66bee.jpg)

**Comment by NoMonsters** [comment]
@PugachA Зачем арминг на САС, какая логика на это завязана?

**Comment by PugachA** [comment]
@NoMonsters Вроде никакой, за arming и ERS один канал отвечает, поэтому и написал, чтобы понятнее было.

**Comment by NoMonsters** [comment]
Оке

**Comment by NoMonsters** [comment]
Светодиод - ОК
Разводка ШИМ сигналов для ERS и канал пульта - ОК

**Comment by NoMonsters** [comment]
Питание и данные модуля телеметрии разместил на плате серв
