### ISSUE TITLE
[Telemetry] Протестировать радиус действия аппаратуры

### ISSUE THREAD

**Issue by PugachA** [PugachA/UnmannedAerialVehicle#93]

**Comment by NoMonsters** [comment]
Протестили радиус, считаем, что она маленький (ну 50 м) п оитгу заказали новый сетап для телемы
@PugachA отпиши плз, что за сетап и закрой ишак

**Comment by PugachA** [comment]
Заказал https://a.aliexpress.com/_AMe7pn
